// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zux6_aaMSVClES5nr_7oMzhqmUbYy_Q',
    appId: '1:281511142464:web:fce3a2e16cec7adf51eba5',
    messagingSenderId: '281511142464',
    projectId: 'america-312a1',
    authDomain: 'america-312a1.firebaseapp.com',
    storageBucket: 'america-312a1.firebasestorage.app',
    measurementId: 'G-FGW5XHVF3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxobWBkEpzwFpPBXofKQLJx0F25ZOtR6g',
    appId: '1:281511142464:android:7cf1539be818aa9c51eba5',
    messagingSenderId: '281511142464',
    projectId: 'america-312a1',
    storageBucket: 'america-312a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGi8sqb2WNSj7Pb0_M1d-rQcHTa2NfA4Q',
    appId: '1:281511142464:ios:a869f2ba2d42a9aa51eba5',
    messagingSenderId: '281511142464',
    projectId: 'america-312a1',
    storageBucket: 'america-312a1.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGi8sqb2WNSj7Pb0_M1d-rQcHTa2NfA4Q',
    appId: '1:281511142464:ios:a869f2ba2d42a9aa51eba5',
    messagingSenderId: '281511142464',
    projectId: 'america-312a1',
    storageBucket: 'america-312a1.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6zux6_aaMSVClES5nr_7oMzhqmUbYy_Q',
    appId: '1:281511142464:web:137d782df6a1f9b951eba5',
    messagingSenderId: '281511142464',
    projectId: 'america-312a1',
    authDomain: 'america-312a1.firebaseapp.com',
    storageBucket: 'america-312a1.firebasestorage.app',
    measurementId: 'G-XLS7MTHXCD',
  );
}
